### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Harrihauki** [tilastokeskus/Minotaurus#1]
ZIP ladattu 2.3.2016 klo 12.30

Tervehdys!

Aihe on mielestäni kiinnostava. Ei ehkä vähiten siksi, että itsekin väsään polunetsintäalgoritmeja.

Dokumentointi on siistiä ja huolellista. Etenkin testausdokumentti. Mainiota katseltavaa.

Testejä muutenkin kiitettävä määrä ja kaikki useammallikin ajolla läpi. Tämä puoli näyttää siis toistaiseksi hyvältä.

Javadocia voisi olla ehkä vähän enemmän. Etenkin, kun projektisi on varsin suuri, niin seuraaminen voisi olla helpompaa. Luokat ja metodit pääsääntöisesti kuitenkin onneksi mukavasti nimettyjä.

Tietorakenteet näyttävät vilkuilullani toimivilta, mikä on hyvä. Useampiakin rakenteita on toteutettu, eli harojoitusta tuohon varmasti tullut kivasti. En kuitenkaan ole ihan varma, voiko vaikkapa HashMapissa käytettyä Map-rajapinnan toteuttamista varsinaisesti laskea oman tietorakenteen toteuttamiseksi. Tosin nyt kirjoittaessa aloin miettiä, että miksi ei laskettaisi. Kun kuitenkin jos kaikki abstraktit metodit toteuttaa itse, niin käytännössä siihen voi sitten vain yksinkertaisesti viitata Mapina ilman, että se sen enempiä varsinaisesti hyödyntäisi valmiita ominaisuuksia. Eli tämä kappale meni nyt vain yleiseksi höpinäksi :D Toivottavasti edes ajatuksia herätti..

Itse algoritmit ovat ilmeisesti vielä vaiheessa, kun Runner-luokalle, jonka käsittääkseni pitäisi tuo puoli hoitaa, en löytänyt perillisiä. Sinänsä sääli, kun olisin halunnut niitä verrata omiin viritelmiini. Mutta ainakin tiedät, minne seuraavaksi!

Ison projektin olet tehnyt. Jos ja kun saat valmiiksi, niin uskon olevan pähee!

**Comment by olavim** [comment]
Kiitos katselmoinnista! Javadocit ovat tosiaan valitettavan vaiheessa, sori siitä. En itsekään näe miksi esimerkiksi Map-rajapinnan toteuttaminen ei olisi hyväksyttyä; itse toteutushan on omaa jälkeä.

Runnereita ei vielä tosiaan ollut kun katselmoinnin teit. Olen tehnyt yhden ja se näkyy tämän päivän palautuksissa, jahka saan viikon hommat kasaan :)
